name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: 'copywork'
          max_timeout: 120
      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_baseUrl: ${{ steps.waitFor200.outputs.url }}
          PROJECT_ID: omho7x4p
          DATASET: copywork
